[package]
name = "owlchess"
version = "0.1.0"
edition = "2021"

[dependencies]
owlchess_base = { path = "../chess_base" }
thiserror = "1.0.31"
arrayvec = "0.7.2"

[build-dependencies]
owlchess_base = { path = "../chess_base" }
rand_xoshiro = "0.6.0"
rand_core = "0.6.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "chess"
harness = false